import { azure, cotre, flexBlocks, mahindra, riode, sirius, venice, vimeo, YBD, creative, archo, trax, learnworld1 } from "../../assets/images"

export const workDetail = [
    {
         id: 11,
        title: "Taxi theory test",
        details: "I developed a comprehensive 'Taxi Theory Test' website in WordPress, featuring multi-language support. The platform includes custom quiz functionality, time-bound assessments, and interactive feedback, providing an efficient learning environment for aspiring taxi drivers.",
        imgAlt: "taxi theory test img",
        imgUrl: learnworld1,
        categories: "Wordpress",
        linkUrl: "https://learnworlds.ch/",
    },
    {
         id: 10,
        title: "Trax",
        details: "This website has been designed in wordress elementor and elementor pro. We are using only elementor and jetengine wordpress plugin to create it.",
        imgAlt: "trax img",
        imgUrl: trax,
        categories: "Wordpress",
        linkUrl: "http://archo.kesug.com/",
    },
    {
        id: 1,
        title: "azure",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "Azure img",
        imgUrl: azure,
        categories: "HTML,CSS,JS",
        linkUrl: "https://azure-app.netlify.app",
    },
    {
        id: 2,
        title: "venice",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "venice img",
        imgUrl: venice,
        categories: "HTML,CSS,JS",
        linkUrl: "https://veniceapp.netlify.app",
    },
    {
        id: 3,
        title: "vimeeo",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "vimeeo img",
        imgUrl: vimeo,
        categories: "HTML,CSS,JS",
        linkUrl: "https://vimeo-app.netlify.app",
    },
    {
        id: 10,
        title: "creative agency",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "creative agency img",
        imgUrl: creative,
        categories: "wordpress",
        linkUrl: "https://creativeagency.kesug.com/",
    },
    {
        id: 11,
        title: "archo",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "archo img",
        imgUrl: archo,
        categories: "WordPress",
        linkUrl: "https://mybios.free.nf",
    },
    {
        id: 5,
        title: "flexBlocks",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "flexBlocks img",
        imgUrl: flexBlocks,
        categories: "React",
        linkUrl: "https://mqasim34.github.io/flexi-blocks/",
    },
    {
        id: 4,
        title: "Corte",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "Corte img",
        imgUrl: cotre,
        categories: "Bootstrap",
        linkUrl: "https://kotre.netlify.app",
    },
    {
        id: 6,
        title: "Mahindra",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "Mahindra img",
        imgUrl: mahindra,
        categories: "Bootstrap,Ajax",
        linkUrl: "https://mahindratractor.netlify.app",
    },
    {
        id: 7,
        title: "riode",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "riode img",
        imgUrl: riode,
        categories: "Bootstrap",
        linkUrl: "https://riode.netlify.app",
    },
    {
        id: 8,
        title: "sirius",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "sirius img",
        imgUrl: sirius,
        categories: "Bootstrap,JS",
        linkUrl: "https://shop-sale.netlify.app",
    },
    {
        id: 9,
        title: "YBD",
        details: "This website has been designed to be simple. We are using front-end technologies like HTML, CSS and JavaScript to create it.",
        imgAlt: "YBD img",
        imgUrl: YBD,
        categories: "Bootstrap,js,jqauery",
        linkUrl: "https://businessdate.netlify.app",
    },

]
